name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe what you'd like.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem are you trying to solve? Is this related to a frustration?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered.

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, code examples, or references.
